# Generated by Django 2.2.7 on 2021-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericbaseview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.CharField(default='Y', max_length=5),
        ),
    ]
